### ISSUE TITLE
de-jekyll-a-hugo-actualizacion-rss

### ISSUE THREAD

**Issue by SidVal** [elbaulp/algui91-hugo#1]
Te leo desde hace tiempo vía RSS.
Ahí salió publicada la entrada a la que hago mención en el título de este issue.
También si googleas "/de-jekyll-a-hugo-actualizacion-rss/", llegas a una URL de tu web que actualmente brinda un bonito 404. Porfa recordá hacer una redirección así no te castigan en términos SEO ;-) 

***

Quería aprovechar para preguntarte por qué migraste de Jekyll a Hugo.
Vas a escribir sobre esto por favor?

***
Desde ya, muchas gracias!

Saludos!

**Comment by elbaulp** [comment]
Hola!, gracias por el apunte, ese post se perdió en el proceso de migración y no me había dado cuenta, ya está redireccionado a la página correcta. Supongo que ahora estás usando los RSSs nuevos, te funcionan bien?

Respecto a la migración, la razón principal era el poder escribir tanto en español como en Inglés. Jekyll actualmente no tiene soporte multi idioma, mientras que Hugo sí. 

Además, en el proceso de migración me dí cuenta que hugo es mucho más rápido, y su sistema de plantillas mucho más cómodo, me permitió simplificar el código a tres únicos ficheros. 


No tenía pensado escribir sobre el tema, pero es una buena idea. Cuando tenga algo más de tiempo quizá lo escriba.


Gracias a tí por leer el blog!

Saludos.
